bump golangci-lint to 1.55.1 and ko to 0.15.0
kubernetes-sigs/release-utils pull request #94
Opened 2023-10-26 06:55 UTC by cpanato

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

- bump golangci-lint to 1.55.1 and ko to 0.15.0

/assign @saschagrunert @xmudrii @Verolop 
cc @kubernetes-sigs/release-engineering 

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
bump golangci-lint to 1.55.1 and ko to 0.15.0
```

2023-10-26 07:17 UTC, saschagrunert requested changes
Can we update https://github.com/kubernetes-sigs/release-utils/blob/main/.golangci.yml to match the latest version as well? Maybe enable linters which do not report anything new?

2023-10-27 08:50 UTC, saschagrunert approved these changes

2023-10-27 08:54 UTC, xmudrii approved these changes

2023-10-27 08:54 UTC, xmudrii commented on .golangci.yml
> +    require-specific: true
Nit: can you please add a new line?

2023-10-27 08:55 UTC, merged